name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker image
      run: |
        IMAGE_BASE="ghcr.io/basalam/kaastolon:$GITHUB_REF_NAME"
        for PG_VERSION in {10..14}
        do
          make PGVERSION=${PG_VERSION} TAG=${IMAGE_BASE}-pg${PG_VERSION} docker
          docker push ${IMAGE_BASE}-pg${PG_VERSION}
        done
