apiVersion: apps/v1
kind: Deployment
metadata:
  name: stolon-slave-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      component: stolon-slave-proxy
      stolon-cluster: kube-stolon
  template:
    metadata:
      labels:
        component: stolon-slave-proxy
        stolon-cluster: kube-stolon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: stolon-slave-proxy
          image: ghcr.io/basalam/kaastolon:v0.19.1-pg10
          command:
            - "/bin/bash"
            - "-ec"
            - |
              exec gosu stolon stolon-proxy
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STPROXY_CLUSTER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['stolon-cluster']
            - name: STPROXY_STORE_BACKEND
              value: "kubernetes"
            - name: STPROXY_KUBE_RESOURCE_KIND
              value: "configmap"
            - name: STPROXY_LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: STPROXY_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:8080"
            - name: STPROXY_SLAVE_NODE_EXPOSURE
              value: "true"
            ## Uncomment this to enable debug logs
            #- name: STPROXY_DEBUG
            #  value: "true"
            ## Uncomment this to enable slave mode
            #- name: STPROXY_SLAVE_NODE_EXPOSURE
            #  value: "true"
          ports:
            - containerPort: 5432
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
